# lang.py

LANGUAGES = {
    'en': {
        'title': "Duck PDF Converter",
        'select_option': "Choose an option:",
        'image_to_pdf': "Image to PDF",
        'pdf_to_image': "PDF to Image",
        'split_pdf': "Split PDF",
        'merge_pdfs': "Merge PDFs",
        'select_images': "Select Image Files:",
        'select_pdf': "Select a PDF File:",
        'choose_pdf': "Choose PDF",
        'add_image': "Add Image",
        'remove_selected': "Remove Selected",
        'convert_to_image': "Convert to Images",
        'convert_to_pdf': "Convert to PDF",
        'back_to_menu': "Back to Menu",
        'select_pdf_split': "Select a PDF File to Split:",
        'split_pdf_button': "Split PDF",
        'select_pdfs_merge': "Select PDF Files to Merge:",
        'add_pdf_files': "Add PDF Files",
        'merge_pdfs_button': "Merge PDFs",
        'description': "This is an open-source software, \nwhich means you should not be charged for using it. \nThe project is available at:\n https://github.com/MeteorCollector/Duck-PDF-Maker",
    },
    '中文（简体）': {
        'title': "鸭子PDF编辑器",
        'select_option': "选择一个选项：",
        'image_to_pdf': "图片转PDF",
        'pdf_to_image': "PDF转图片",
        'split_pdf': "拆分PDF",
        'merge_pdfs': "合并PDF",
        'select_images': "选择图片文件：",
        'select_pdf': "选择PDF文件：",
        'choose_pdf': "选择 PDF",
        'add_image': "添加图片",
        'remove_selected': "移除选中",
        'convert_to_image': "转换为图片",
        'convert_to_pdf': "转换为PDF",
        'back_to_menu': "返回菜单",
        'select_pdf_split': "选择要拆分的PDF文件：",
        'split_pdf_button': "拆分PDF",
        'select_pdfs_merge': "选择要合并的PDF文件：",
        'add_pdf_files': "添加PDF文件",
        'merge_pdfs_button': "合并PDF",
        'description': "这是一个开源软件，\n这意味着你不应该因为使用该软件而被收费。\n该项目地址：\n https://github.com/MeteorCollector/Duck-PDF-Maker",
    }
}
